### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by DemianTinkiel** [blockbridge/blockbridge-docker-volume#14]
1. Is this project still alive. I see the last commit in 2019 and last (and only?) release in 2016
2. Has there been any plans for asimilar approach for podman

**Comment by ikrel** [comment]
Hi Demian, the software provided via this repository is still alive and functional. It will continue to be as long as Docker volume API does not change.
Keep in mind that Blockbridge Docker Volume Plugin is a driver/proxy between Docker API and Blockbridge API in our primary software - https://www.blockbridge.com, which is constantly evolving and improving.

There are currently no plans for podman support. Most of our container utilizing customers use Kubernetes ( https://www.blockbridge.com/kubernetes/ ).
